---
title: uBuild Design Blocks
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
author: Forestry.io
email: support@forestry.io
description: ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks
  feature. This theme provides a set of page-level components and a pre-configured
  Forestry Blocks UI that will empower content editors to construct their own webpages.
baseurl: "/ubuild-jekyll"
url: ''
plugins:
- jekyll-feed
- jekyll-menus
